web:
   build: ./docker_build/nginx/
   links:
      - mysql
   ports:
      - "80:80"
   volumes:
      - ./html:/var/www/html

mysql:
   image: mysql:5.6
   environment:
      - MYSQL_ROOT_PASSWORD=*bsolus#bs
   volumes:
      - ./_data/data:/var/lib/mysql

cloud9:
   image: kdelfour/cloud9-docker
   ports:
      - "80"
   volumes:
      - ./html:/workspace/
